const typeActionProduct = {
  GET_ID_PRODUCT: 'GET_ID_PRODUCT',
  GET_ID_PRODUCT_SUCCESS: 'GET_ID_PRODUCT_SUCCESS',
  GET_ID_PRODUCT_FAIL: 'GET_ID_PRODUCT_FAIL',
  GET_REVIEWS_PRODUCT: 'GET_REVIEWS_PRODUCT',
  GET_REVIEWS_PRODUCT_SUCCESS: 'GET_REVIEWS_PRODUCT_SUCCESS',
  GET_REVIEWS_PRODUCT_FAIL: 'GET_REVIEWS_PRODUCT_FAIL',
  GET_LIST_PRODUCT: 'GET_LIST_PRODUCT',
  GET_LIST_PRODUCT_SUCCESS: 'GET_LIST_PRODUCT_SUCCESS',
  GET_LIST_PRODUCT_FAIL: 'GET_LIST_PRODUCT_FAIL',
  POST_LIKE_PRODUCT: 'POST_LIKE_PRODUCT',
  POST_LIKE_PRODUCT_SUCCESS: 'POST_LIKE_PRODUCT_SUCCESS',
  POST_LIKE_PRODUCT_FAIL: 'POST_LIKE_PRODUCT_FAIL',
  ADD_TO_CART_API: 'ADD_TO_CART_API',
  ADD_TO_CART_API_SUCCESS: 'ADD_TO_CART_API_SUCCESS',
  ADD_TO_CART_API_FAIL: 'ADD_TO_CART_API_FAIL',
  GET_CART_API: 'GET_CART_API',
  GET_CART_API_SUCCESS: 'GET_CART_API_SUCCESS',
  GET_PRODUCT_FAVORITE: 'GET_PRODUCT_FAVORITE'
}

export const urlApi = {
  // chosse 1 product make show detail product
  GET_PRODUCT_DETAIL: '/products/',
  // filter product same attr
  GET_ALL_PRODUCT: '/products',
  // reviews product in product detail page
  GET_LIST_REVIEWS: '/products/4/reviews',
  GET_PRODUCT: '/products/',
  GET_REVIEWS: '/reviews',
  // vote product
  GET_ASSESSMENT_REVIEW: '/products/4/assessment-reviews',
  POST_LIKE_PRODUCT_API: '/user/favorite-products'
}

export default typeActionProduct
