export const typeActions = {
  INCREASE_CART_PRODUCT: 'INCREASE_CART_PRODUCT',
  DECREASE_CART_PRODUCT: 'DECREASE_CART_PRODUCT',
  ID_DELETE_PRODUCT: 'ID_DELETE_PRODUCT',
  GET_CART_PROGRESS_API: 'GET_CART_PROGRESS_API',
  GET_CART_PROGRESS_API_SUCCESS: 'GET_CART_PROGRESS_API_SUCCESS',
  GET_CART_PROGRESS_API_FAIL: 'GET_CART_PROGRESS_API_FAIL'
}
